dist: xenial
os: linux
language: java
jdk:
  - openjdk8

install: true

env:
  global:
    - CI_CLEANUP=ci/tmp/cleanup.sh
    - GCP_SECRET_FILENAME=gcp-secret.json

jobs:
  include:
    - name: Direct IT
      script: ci/run-tests.sh 'direct'
    - name: Dataflow IT
      script: ci/run-tests.sh 'dataflow'
    - name: Direct Samples
      script: ci/run-samples-tests.sh 'direct'

before_install:
  - echo "No pre-installs at this time"

before_script:
  # Get GCP service account credentials
  - echo $GCP_SECRET | base64 -d > "./${GCP_SECRET_FILENAME}"
  - export GOOGLE_APPLICATION_CREDENTIALS="${PWD}/${GCP_SECRET_FILENAME}"
  # Create cleanup script
  - mkdir -p "${CI_CLEANUP%/*}" && touch "$CI_CLEANUP" && chmod +x "$CI_CLEANUP"

after_success:
  - echo "Test Success - Branch( $TRAVIS_BRANCH ) Pull Request( $TRAVIS_PULL_REQUEST ) Tag( $TRAVIS_TAG )"

after_script:
  - $CI_CLEANUP
  - rm "$GCP_SECRET_FILENAME"
  # Need to give some time for output buffer to finish
  - sleep 10
